# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuforia_target_id', models.CharField(max_length=200)),
                ('content_name', models.CharField(max_length=100)),
                ('view_count', models.IntegerField()),
                ('view_count_limit', models.IntegerField()),
                ('view_state', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlar.User')),
            ],
        ),
    ]
