# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0002_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='view_count_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='view_state',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='vuforia_target_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
