# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0003_auto_20170607_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='img_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='content_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
