# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0004_auto_20170617_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=300, null=True)),
                ('oauth_token_secret', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
