# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0005_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth',
            name='access_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='oauth',
            name='access_token_secret',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
