# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0006_auto_20170627_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hlar.Oauth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_file_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
