# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0007_auto_20170627_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
