# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0010_auto_20170628_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
