# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0012_auto_20170705_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
    ]
