# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0014_auto_20170811_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 10, 15, 43, 35, 700708, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
