# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0017_auto_20170925_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlar.Target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
