# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0019_target_del_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_link_URL',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
