# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlar', '0021_auto_20171225_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
